### ISSUE TITLE
Tabbed Content - Carousel

### ISSUE THREAD

**Issue by garthus** [tangentlabs/django-oscar-fancypages#10]
When we add a content block which is a carousel to a tabbed block its not quite working - the carousel is a bit broken - see here:

click on the fiction tab

http://glitterbox.tangentsnowball.com.au/dashboard/fancypages/customise/1/

**Comment by informa** [comment]
Fixed this issue.

**Comment by garthus** [comment]
This is still not working on Glitterbox - see this page:

http://glitterbox.tangentsnowball.com.au/dashboard/fancypages/customise/1/

**Comment by roadsideseb** [comment]
Are you referring to the widget in the left column? This only seems to be an issue in Chrome, FF does it alright. I know I'm not a FED but thought this insight might help :)
